// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_De_Funcionarios_MVC.Data;

#nullable disable

namespace Sistema_De_Funcionarios_MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106131241_CriarBanco")]
    partial class CriarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_De_Funcionarios_MVC.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalarioBase")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TabelaFuncionario");

                    b.HasDiscriminator<string>("Cargo").HasValue("Funcionario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Sistema_De_Funcionarios_MVC.Models.Gerente", b =>
                {
                    b.HasBaseType("Sistema_De_Funcionarios_MVC.Models.Funcionario");

                    b.HasDiscriminator().HasValue("Gerente");
                });

            modelBuilder.Entity("Sistema_De_Funcionarios_MVC.Models.Vendedor", b =>
                {
                    b.HasBaseType("Sistema_De_Funcionarios_MVC.Models.Funcionario");

                    b.HasDiscriminator().HasValue("Vendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
